# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    args:
    - --profile
    - black
    - --filter-files
- repo: https://github.com/psf/black
  rev: 21.6b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
- repo: https://github.com/kumaraditya303/mirrors-pyright
  rev: v1.1.150
  hooks:
  - id: pyright
    types_or:
    - python
    - pyi
